---
- name: Installation du serveur Bidon
  hosts: groupebidon
  remote_user: userUser
  tasks:
          - name: Ajout de repository manquant
            yum_repository:
              name: epel
              description: EPEL YUM repo
              baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

          - name: Installation des logiciels prerequis
            yum:
              update_cache: yes
              name: "{{ item }}"
              state: latest
            with_items:
              - git.x86_64
              - geany.x86_64
              - elinks.x86_64
              - htop.x86_64
